### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by funkyremi** [funkyremi/meteor-boilerplate#1]
- [ ] Beautiful emails templates ( meteor add cmather:handlebars-server )
- [ ] Useraccount:iron-routing Useraccount:bootstrap
- [ ] Landing page -> connection to app (if currentuser app else landing)
- [ ] Editor config (eslint
- [ ] i18n français english
- [ ] mobile config
- [ ] collection security
- [ ] gitignore
- [ ] settings.json
- [ ] Fixtures (user, roles...)
- [ ] Alaning roles
- [ ] Simple tests (unit and end to end basics)
- [ ] Mup config
- [ ] Simpleschema and autoform basics
- [ ] Bootstrap + flatui package
- [ ] Must have packages ( meteor add softwarerero:accounts-t9n useraccounts:bootstrap useraccounts:iron-routing gwendall:impersonate accounts-password accounts-base alanning:roles ongoworks:security session cmather:handlebars-server check ejson iron:router less email momentjs:moment random matb33:collection-hooks manuel:reactivearray flowkey:hotkeys fortawesome:fontawesome danappelxx:hover.css twbs:bootstrap themeteorchef:bert kevohagan:sweetalert tap:i18n tap:i18n-ui jss:flag-icon meteorhacks:fast-render meteorhacks:subs-manager meteortoys:allthings )
